### ISSUE TITLE
Fails on Julia v1.7

### ISSUE THREAD

**Issue by oschulz** [jstrube/FastJetWrapBuilder#2]
The FastJet_Julia_Wrapper_jll currently forces libcxxwrap_julia_jll to v0.8.5, which is not compatible with Julia v1.7 (I think libcxxwrap_julia_jll 0.8.8 is).

**Comment by jstrube** [comment]
I think this should work now.
Can you please check? Note that this will probably pull in the new FastJet 3.4.0 as a side effect.

**Comment by oschulz** [comment]
> Can you please check? 

Loads just fine now - thanks!
